swaybar: use text subpixel antialias only where it would look good
swaywm/sway pull request #5623
Opened 2020-08-14 18:22 UTC by Fenveireth

Addresses #5605

Text Subpixel antialiasing is :

- FreeType makes glyph bitmaps containing coverage percentage for each
  subpixel, instead of pixel
- Then draw by performing the blend for each subpixel, instead of pixel (e.g.
  dual-source blending in opengl)

And there's only one Alpha channel, so this extra coverage data can't
leave Cairo to reach the compositor through there.
Therefore, it can't work as intended if output text alpha != bar background
alpha. Disable it for those cases, enable it elsewhere

As for color emojis, they are RGBA bitmaps. If drawn with text alpha=1.0
and background alpha=1.0 (should be completely opaque bar), then with
'CAIRO_OPERATOR_SOURCE' texels with alpha < 1.0 result in a blend with
whatever's behind the bar, instead of the bar background

2020-08-14 18:41 UTC, Fenveireth commented
I would rather have 'OVER' for everything, but it would ruin it for setups setting all colors with a same <1 opacity, to produce the same result as an opaque bar drawn whole with that opacity value.
And that's the normal way to get a translucent bar, right ?

2020-11-03 06:06 UTC, Xyene reviewed
Thanks for working on this! This matches my (albeit rudimentary) understanding of how subpixel aliasing works, and sounds like a good compromise. I've nitted a few things in the code, but on the most part this looks good. Please also squash the commits into one when you're done.

/ping @emersion from original thread

2021-02-23 02:47 UTC, Xyene requested changes
Argh, sorry, this got lost in my emails... just some stylistic things and I think this should be good to go.

Feel free to ping me if I I don't reply, it probably means I've lost the notification.

2021-02-23 02:47 UTC, Xyene commented on swaybar/render.c
> +static uint32_t render_binding_mode_indicator(struct render_call* ctx,
Nit: `struct render_call *ctx`.

2021-02-23 02:47 UTC, Xyene commented on swaybar/render.c
> +static uint32_t render_to_cairo(struct render_call* ctx) {
(same)

2021-02-23 02:47 UTC, Xyene commented on swaybar/render.c
> +struct render_call {
Given that this is replacing `cairo_t *cairo` in most places, perhaps `struct render_context`/`cairo_context`/`cairo_state` (or similar) is a better name?

2021-02-23 02:47 UTC, Xyene commented on swaybar/render.c
> +	struct render_call ctx;
Nit: `ctx = { 0 }` so we don't get garbage pointers in coredumps in case we forget to initialize a field.

2021-02-23 02:47 UTC, Xyene commented on swaybar/render.c
> +	cairo_t *cairo = ctx->cairo;
Tiny nit: `cairo` is not used until later, so this declaration could be moved to ~line 94.

2021-02-23 02:47 UTC, Xyene commented on swaybar/render.c
> +	cairo_t *cairo = ctx->cairo;
(same, try to keep declarations close to where they're used)

2021-02-23 07:57 UTC, emersion commented on swaybar/render.c
> +static uint32_t render_status_line_i3bar(struct render_call* ctx, double *x) {
Style: `*` on the right

2021-03-08 00:18 UTC, Xyene approved these changes
LGTM, thanks for working on this!

2021-03-08 00:18 UTC, merged