config: check the return value of xkb_context_new
swaywm/sway pull request #5705
Opened 2020-09-23 15:33 UTC by jhofstee

When xkb_context_new returns NULL and that is passed on to
xkb_keymap_new_from_names, sway will crash. This happens for example
if xkeyboard-config is not installed. Exit with an error message instead.

While at it, check xkb_keymap as well.

2020-10-18 20:04 UTC, emersion commented on sway/config.c
> +	if (!context)
Style: braces are mandatory

2020-10-18 20:04 UTC, emersion commented on sway/config.c
> +	if (!xkb_keymap)
Ditto

2020-10-18 20:05 UTC, emersion commented on sway/config.c
> +		sway_abort("Failed to create XKB context");
We shouldn't crash on this, instead we should log the error and return NULL.

2020-10-18 20:05 UTC, emersion requested changes
Thanks for your PR! Here are some comments.

2020-10-19 20:19 UTC, closed without merging

2021-01-22 15:31 UTC, george-hopkins commented
@jhofstee Thank you for the patch, it helped me narrowing down an issue I had. Do you intend to keep working on it or would you mind if someone else would take over?

2021-02-13 21:34 UTC, jhofstee commented
> @jhofstee Thank you for the patch, it helped me narrowing down an issue I had. Do you intend to keep working on it or would you mind if someone else would take over?

A bit late, but feel to take over.