Make the language in README zh_CN more native
swaywm/sway pull request #6939
Opened 2022-04-11 12:09 UTC by FrozenArcher

As a native Chinese speaker, I found the language in the origin Chinese README not so readable, so I tried to fix it.
(my first pull request in my life QAQ)

2022-04-11 12:33 UTC, emersion commented
Thanks for your PR! It would be nice if another Chinese speaker could review it.

cc @SuccessGo @3TUSK

2022-04-13 05:30 UTC, 3TUSK requested changes
I was summoned. (By the way how did you know me?)

2022-04-13 05:30 UTC, 3TUSK commented on README.zh-CN.md
> +发行以 [E88F5E48](https://keys.openpgp.org/search?q=34FF9526CFEF0E97A340E2E40FDE7BE0E88F5E48) 签名并发布在 [GitHub](https://github.com/swaywm/sway/releases)上。
```suggestion
每个发布版本都以 [E88F5E48](https://keys.openpgp.org/search?q=34FF9526CFEF0E97A340E2E40FDE7BE0E88F5E48) 的密钥签名并发布在 [GitHub](https://github.com/swaywm/sway/releases)上。
```

2022-04-13 07:50 UTC, emersion commented
> By the way how did you know me?

You were involved in the pull request adding the Chinese translation a few years back. :)

2022-04-13 12:36 UTC, FrozenArcher commented
改的好 -_-b

2022-04-13 12:40 UTC, FrozenArcher commented
There's one more question: there're differences between English README and the Chinese one.

2022-04-13 12:42 UTC, emersion commented
Yeah, translated READMEs often lag behind the English one. Would it be possible to sync up the Chinese README?

2022-04-14 02:12 UTC, FrozenArcher commented
> Yeah, translated READMEs often lag behind the English one. Would it be possible to sync up the Chinese README? (Can be a separate PR if you prefer to get the current changes landed first.)

That's fine. But I'm only available on weekends. I'll do that this weekend.

2022-04-14 02:15 UTC, FrozenArcher commented
I think the zh_TW README is translated very well.

2022-04-17 05:11 UTC, FrozenArcher commented
> Yeah, translated READMEs often lag behind the English one. Would it be possible to sync up the Chinese README? (Can be a separate PR if you prefer to get the current changes landed first.)

I've already created a new one. This will be closed.

2022-04-17 05:11 UTC, closed without merging